apiVersion: v1
kind: Service
metadata:
  name: base-api-service
spec:
  selector:
    app: base-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort